name: 

on:
  push:
    branches:

env:
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  AWS_REGION: 

jobs:
  # Configure AWS credentials 
  configure_aws_credentials:
    name: Configure AWS credentials
    runs-on: 
    steps:
      - name: 
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: 
          aws-secret-access-key: 
          aws-region: 
